sudo: required
language: none

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get install -y bash curl
  - docker build -t worker $TRAVIS_BUILD_DIR/.ci

matrix:
  include:
    - env: CI_TARGET=debug

    - env: CI_TARGET=release
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: $TRAVIS_BUILD_DIR/build-release/doc/html
        on:
          branch: add-travis-ci

    - env: CI_TARGET=coverage
      after_success: bash <(curl -s https://codecov.io/bash) -g "*/test/*"

    - env: CI_TARGET=lint

script: docker run -w /workspace -v $TRAVIS_BUILD_DIR:/workspace worker .ci/$CI_TARGET.sh
